[project]
name = "wan2-2-fast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = 'PRITHIVMLMODS\prith', email = "prithivsakthi676@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "accelerate==1.14.0",
    "diffusers==0.39.0",
    "ftfy==6.3.1",
    "gradio==6.22.0",
    "huggingface-hub>=1.27.0",
    "imageio==2.37.4",
    "imageio-ffmpeg==0.6.0",
    "opencv-python==5.0.0.93",
    "peft==0.20.0",
    "pillow==12.3.0",
    "safetensors==0.8.0",
    "sentencepiece==0.2.2",
    "spaces==0.51.1",
    "torch==2.11.0",
    "torchao==0.18.0",
    "torchvision==0.26.0",
    "transformers==5.15.0",
]

[project.scripts]
wan2-2-fast = "wan2_2_fast:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
